### ISSUE TITLE
white space inside url datatype

### ISSUE THREAD

**Issue by imahdio** [imahdio/CSS-Essential-Training#16]
I'm studying  Web fonts with @font-face  lesson [from here](http://168.119.85.43/css-essential-training-3/05-Typography/)

The instructor said:
![image](https://user-images.githubusercontent.com/64577273/149832148-8c929c28-86e4-4693-8cc1-888aa546fecd.png)
>When using the URL functional datatype, single or double quotes are optional unless the URL value itself contains a parenthesis, commas, white space, single quotes, or double quotes. If it does contain any of these characters, it must be enclosed in quotes or escaped with a backslash. 

but based my test and tries witht he following code snippet , white space inside URL values are acceptable without quotes.
does the instructor claim that by a mistake or there is any other reason for it?
[download related woff font in here](https://www.dropbox.com/s/wyh6javlwo6c5c6/Branda-yolq.woff?dl=0)
```html
<!DOCTYPE html>
<html>
<head>
<style> 
@font-face {
  font-family: Branda yolq;
  src: url(Branda-yolq.woff);
}

div {
  font-family: Branda yolq;
}
</style>
</head>
<body>

<h1>The @font-face Rule</h1>

<div>With CSS, websites can finally use fonts other than the pre selected "web-safe" fonts.</div>

</body>
</html>
```
![image](https://user-images.githubusercontent.com/64577273/149831724-cddef4ae-3f10-4541-942b-702cfb4f1651.png)

**Comment by MRGHOSJ** [comment]
Better use quotes because it's recommended by the newest standard and there're fewer edge cases.

The W3C says quotes are optional, all three of your ways are legal.

Opening and closing quote just need to be the same character.

If you have special characters in your URL, you should use quotes or escape the characters.

The unquoted version is only supported for legacy reasons and needs special parsing rules (for escape sequences, etc.), thus being cumbersome and not supporting url-modifiers.

That means, the url(...) syntax is supposed to be a functional notation, which takes a string and a url-modifier as parameters. Use the quote notation (which produces a string token) would be more standard-compliant and introduce less complexity.

**Comment by freelancerasadm** [comment]
It is better to use quotes because it is recommended by the new standard and in the case of low edges
The W3C says quotes are optional, your three ways are legal.
The opening and closing quotes must be the same characters.
If your URL contains special characters, you should use citations or skip the characters
The cited version is only supported due to inheritance and requires special parsing rules (for escape sequences, etc.), thus does not support cumbersome and URL-correctors.
That is, the URL (...) syntax is supposed to be a functional notation, taking a string and a URL-modifier as parameters. Using quotation notation (which creates a string token) will be more standardized and introduce less complexity.

**Comment by imahdio** [comment]
> I'm studying Web fonts with @font-face lesson [from here](http://168.119.85.43/css-essential-training-3/05-Typography/)
> 
> The instructor said: ![image](https://user-images.githubusercontent.com/64577273/149832148-8c929c28-86e4-4693-8cc1-888aa546fecd.png)
> 
> > When using the URL functional datatype, single or double quotes are optional unless the URL value itself contains a parenthesis, commas, white space, single quotes, or double quotes. If it does contain any of these characters, it must be enclosed in quotes or escaped with a backslash.
> 
> but based my test and tries witht he following code snippet , white space inside URL values are acceptable without quotes. does the instructor claim that by a mistake or there is any other reason for it? [download related woff font in here](https://www.dropbox.com/s/wyh6javlwo6c5c6/Branda-yolq.woff?dl=0)
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
> <style> 
> @font-face {
>   font-family: Branda yolq;
>   src: url(Branda-yolq.woff);
> }
> 
> div {
>   font-family: Branda yolq;
> }
> </style>
> </head>
> <body>
> 
> <h1>The @font-face Rule</h1>
> 
> <div>With CSS, websites can finally use fonts other than the pre selected "web-safe" fonts.</div>
> 
> </body>
> </html>
> ```
> 
> ![image](https://user-images.githubusercontent.com/64577273/149831724-cddef4ae-3f10-4541-942b-702cfb4f1651.png)

in this issue , I mistake the value of url functional datatype with font-family
and reach into some uncommon results
Now and after this clarification , there is not any doubts with instructor quotations.
